substitutions:
  name: athom-smart-plug-v2-a7962e
  friendly_name: Panel Heater Plug
  sntp_server_1: au.pool.ntp.org
  sntp_server_2: au.pool.ntp.org
  sntp_server_3: au.pool.ntp.org
packages:
#  Athom_Technology.Smart_Plug_V2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
  remote_package:
    url: https://github.com/s3n3rgy/ESPHome.git
    ref: main
    refresh: always
    files: 
      - components/athom/smart-plug-v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: jl5wBJOn3HXViXbbVEVxI6HrB/WArIOiKBzH80km0rs=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
