esphome:
  name: esphome-web-45e6ec
  friendly_name: Study Presence V3
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev



substitutions:
  device_id: study-presence
  pwd: !secret pwd
  web_server_port: "80"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: !secret api_key
  log_level: debug  #debug info warn error none
  log_baud_rate: "115200"  #11520 is default, 0 for none
  time_platform: "homeassistant"
  uart_tx: GPIO17 #Used for LD2410 Radar
  uart_rx: GPIO16 #Used for LD2410 Radar
  i2c_sda_pin: GPIO21 
  i2c_scl_pin: GPIO22
#  bmp580_address: "0x47" #Address of BMP580 Temp Sensor.
  bme680_address: "0x77" #Address of BME680 Temp Sensor.
  vmel7700_address: "0x10"  #Address of VMEL7700 Light Sensor
  pir_gpio: "GPIO13"  #AM312 PIR motion sensor connected to


#git repo
packages:
  remote_package_files:
    url: https://github.com/s3n3rgy/ESPHome.git
    ref: main
    refresh: always
    files: 
      - packages/ota/ota.yaml
      - packages/web/web_server.yaml
      - packages/api/api.yaml
      - packages/sensors/board_status.yaml
      - packages/binary_sensor/status.yaml
      - packages/wifi/wifi_dhcp.yaml
      - packages/logger/logger.yaml
      - packages/text_sensor/version.yaml
      - packages/text_sensor/wifi_info.yaml
      - packages/button/restart.yaml
      - packages/time/time.yaml
      - packages/protocol/i2c.yaml  #include when using any i2c sensors
#      - packages/component/bmp580_temp.yaml  #include if connecting the BMP580 Temp and pressure Sensor
      - packages/component/bme680_temp.yaml  #include if connecting the BMP580 Temp and pressure Sensor
      - packages/component/veml7700_lux.yaml  #include if connecting to VEML7700 Light Sensor
      - packages/component/am312_pir.yaml #include with PIR Sensors
      - packages/component/ld2410_radar.yaml #LD2410 Radar
