##DO NOT UPGRADE FROM 2025.5.2##

esphome:
  name: esphome-web-33233c
  friendly_name: TCL Aircon
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev

substitutions:
  device_name: esphome_web_33233c
  device_id: tcl_aircon
  humanly_name: TCL Aircon
  uart_rx: GPIO1 #used for Aircon/uart_logger
  uart_tx: GPIO3 #used for Aircon/uart_logger
  uart1_baud: 0 #11520 is default, 0 for TCL Aircon
  uart_rx2: GPIO16 #Used for LD2410 Radar
  uart_tx2: GPIO17 #Used for LD2410 Radar
  uart2_baud: 11520 #11520 is default
  receive_led: GPIO2
  transmit_led: GPIO2
  i2c_sda_pin: GPIO21 
  i2c_scl_pin: GPIO22
  vmel7700_address: "0x10"  #Address of VMEL7700 Light Sensor
 # log_level: none  #debug info warn error none
 # log_baud_rate: "0"  #11520 is default, 0 for none
  time_platform: "homeassistant"
  pwd: !secret pwd
  web_server_port: "80"
  api_key: !secret api_key
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

packages:
  remote_package:
    url: https://github.com/s3n3rgy/ESPHome.git
    ref: Dev
    refresh: always
    files:
      - packages/ota/ota.yaml
      - packages/web/web_server.yaml
      - packages/api/api.yaml
      - packages/sensors/board_status.yaml
      - packages/binary_sensor/status.yaml
      - packages/wifi/wifi_dhcp.yaml
#      - packages/logger/logger.yaml
      - packages/text_sensor/version.yaml
      - packages/text_sensor/wifi_info.yaml
      - packages/button/restart.yaml
      - packages/time/time.yaml
      - packages/protocol/i2c.yaml  #include when using any i2c sensors
      - packages/protocol/uart.yaml
      - packages/component/tcl_aircon.yaml
      - packages/component/ld2410_radar.yaml #LD2410 Radar
      - packages/component/veml7700_lux.yaml  #include if connecting to VEML7700 Light Sensor
