##Hardware State

#globals:
#  - id: cpu_speed
 #   type: int
 #   restore_value: no
 #   initial_value: "0"

#Exposes configuration and status sensors
sensor:
    #Device UPTIME
  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s
    #Device CPU Speed  - Not working
#  - platform: debug
#    name: "ESP CPU Speed"
#    id: cpu_frequency
#    accuracy_decimals: 0
#    unit_of_measurement: Mhz
#    entity_category: "diagnostic"
    #Device Memory
  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: "kB"
    state_class: measurement
    entity_category: "diagnostic"
    #Device Temperature
  - platform: template
    id: sys_esp_temperature
    name: ESP Temperature
    lambda: return temperatureRead();
    unit_of_measurement: °C
    device_class: TEMPERATURE
    update_interval: 60s
    entity_category: "diagnostic"
    #Device RSSI
  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
