#https://esphome.io/components/sensor/bme68x_bsec2/
#include packages/protocol/i2c.yaml
bme68x_bsec2_i2c:
  model: bme680
  id: ${bme680_id}
  address: ${bme680_address}
  temperature_offset: 0
  operating_age: 4d #4days or 28d days
  sample_rate: lp #lp=3s, ulp=5min
  i2c_id: bus_a
  
sensor:
  - platform: bme68x_bsec2_i2c
    bme68x_bsec2_id: ${bme680_id}
    temperature:
      name: "Temperature"
      filters:
        - median
    pressure:
      name: "Pressure"
      filters:
        - median      
    humidity:
      name: "Humidity"
      filters:
        - median
    gas_resistance:
      name: "Gas Resistance"
      filters:
        - median
    iaq: # IAQ accuracy as a numeric value of 0, 1, 2, 3
      name: "IAQ"
      id: iaq
    co2_equivalent: #ppm
      name: "CO2 Equivalent"
    breath_voc_equivalent:  #Volatile organic compounds equivalent estimate in ppm
      name: "Breath VOC Equivalent"
      filters:
        - median

text_sensor:
  - platform: bme68x_bsec2_i2c
    bme68x_bsec2_id: ${bme680_id}
    iaq_accuracy: # IAQ accuracy as a text value of Stabilizing, Uncertain, Calibrating, Calibrated
      name: "IAQ Accuracy"

  - platform: template
    name: "IAQ Classification"
    icon: "mdi:checkbox-marked-circle-outline"
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        return {"Excellent"};
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return {"Good"};
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return {"Lightly polluted"};
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return {"Moderately polluted"};
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return {"Heavily polluted"};
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return {"Severely polluted"};
      }
      else if (int(id(iaq).state) >= 351) {
        return {"Extremely polluted"};
      }
      else {
        return {"error"};
      }
