#BME680 Temp, pressure, humidity, vox, 
#include packages/protocol/i2c.yaml
sensor:
  - platform: bme680
    i2c_id: bus_a
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"
      oversampling: 16x
    humidity:
      name: "Humidity"
    gas_resistance:
      name: "Gas Resistance"
    address: ${bme680_address} 
    update_interval: 60s
