#BMP580 Temp and pressure sensor, use bmp581 platform
#include packages/protocol/i2c.yaml
sensor:
  - platform: bmp581
    i2c_id: bus_a
    temperature:
      name: "Temperature"
      oversampling: 4x
    pressure:
      name: "Pressure"
      oversampling: 16x
    address: ${bmp580_address} 
  #  address: 0x47
    update_interval: 60s  
