#for VENL700 Light sensor
#include packages/protocol/i2c.yaml
#framework: type: arduino (not esp-idf compatible)
#defaul address 0x10

sensor:
  - platform: veml7700
    i2c_id: bus_a
    address: ${vmel7700_address}
    update_interval: 60s
    ambient_light: 
      name: "Ambient light"
    full_spectrum: 
      name: "Full Spectrum"
