substitutions:
  #flash_write_interval: 10min

esphome:
  name: ${device_id}
  friendly_name: ${device_name}
  name_add_mac_suffix: false
#  build_path: ./build/${device_id}

${platform}:
  board: ${board}

#preferences:
#  flash_write_interval: ${flash_write_interval}
